### ISSUE TITLE
发送交易时有时会报错

### ISSUE THREAD

**Issue by liuxh-go** [bnb-chain/go-sdk#92]
有时能成功的发送交易,但有时会报错,错误信息:context deadline exceeded
但是我通过网页钱包查看交易记录是有交易记录的

**Comment by guagualvcha** [comment]
请问你用的是rest-cliet 还是rpc client，默认设置是2秒超时

**Comment by wshhz** [comment]
rpc client,直接调用方法就报错了，没有到2秒

**Comment by hoangphuongcs** [comment]
english pls :D

**Comment by wshhz** [comment]
Sometimes it can successfully send a transaction, but sometimes it will report an error, the error message: context deadline exceeded
But I check the transaction history through the web wallet and there is a transaction record and the transfer is successful.
